### ISSUE TITLE
Support Verdaccio with Active Directory authentication

### ISSUE THREAD

**Issue by LayZeeDK** [Turbo87/auto-dist-tag#8]
When I use Verdaccio with Active Directory authentication, `auto-dist-tag` queries NPM for the released packages instead of Verdaccio.

I have configured NPM CLI to use Verdaccio as a registry, using `npm set registry http://my.verdaccio.hostname`.

`package-json` states this
> Both public and private registries are supported, for both scoped and unscoped packages, as long as the registry uses either bearer tokens or basic authentication.

However, it doesn't seem that Verdaccio with Active Directory authentication uses either.

**Comment by Turbo87** [comment]
Could you open an issue about this on the `package-json` project? I don't think there is much we can do about it if the underlying project is not supporting it.

**Comment by LayZeeDK** [comment]
Issue moved to https://github.com/sindresorhus/package-json/issues/39
